#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LoginSystem.Resource", IsApplication=true)]

namespace LoginSystem
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLAppConfig.FileSystemStream.Android.Resource.Boolean.abc_action_bar_embed_tabs = global::LoginSystem.Resource.Boolean.abc_action_bar_embed_tabs;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Color.primary_text_default_material_dark = global::LoginSystem.Resource.Color.primary_text_default_material_dark;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Color.ripple_material_light = global::LoginSystem.Resource.Color.ripple_material_light;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Color.secondary_text_default_material_dark = global::LoginSystem.Resource.Color.secondary_text_default_material_dark;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Color.secondary_text_default_material_light = global::LoginSystem.Resource.Color.secondary_text_default_material_light;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Dimension.notification_large_icon_height = global::LoginSystem.Resource.Dimension.notification_large_icon_height;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Dimension.notification_large_icon_width = global::LoginSystem.Resource.Dimension.notification_large_icon_width;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Dimension.notification_subtext_size = global::LoginSystem.Resource.Dimension.notification_subtext_size;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Drawable.notification_template_icon_bg = global::LoginSystem.Resource.Drawable.notification_template_icon_bg;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Id.action0 = global::LoginSystem.Resource.Id.action0;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Id.action_divider = global::LoginSystem.Resource.Id.action_divider;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Id.cancel_action = global::LoginSystem.Resource.Id.cancel_action;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Id.chronometer = global::LoginSystem.Resource.Id.chronometer;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Id.end_padder = global::LoginSystem.Resource.Id.end_padder;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Id.icon = global::LoginSystem.Resource.Id.icon;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Id.info = global::LoginSystem.Resource.Id.info;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Id.line1 = global::LoginSystem.Resource.Id.line1;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Id.line3 = global::LoginSystem.Resource.Id.line3;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Id.media_actions = global::LoginSystem.Resource.Id.media_actions;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Id.normal = global::LoginSystem.Resource.Id.normal;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Id.status_bar_latest_event_content = global::LoginSystem.Resource.Id.status_bar_latest_event_content;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Id.text = global::LoginSystem.Resource.Id.text;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Id.text2 = global::LoginSystem.Resource.Id.text2;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Id.time = global::LoginSystem.Resource.Id.time;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Id.title = global::LoginSystem.Resource.Id.title;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Integer.cancel_button_image_alpha = global::LoginSystem.Resource.Integer.cancel_button_image_alpha;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Integer.status_bar_notification_info_maxnum = global::LoginSystem.Resource.Integer.status_bar_notification_info_maxnum;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Layout.notification_media_action = global::LoginSystem.Resource.Layout.notification_media_action;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Layout.notification_media_cancel_action = global::LoginSystem.Resource.Layout.notification_media_cancel_action;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Layout.notification_template_big_media = global::LoginSystem.Resource.Layout.notification_template_big_media;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Layout.notification_template_big_media_narrow = global::LoginSystem.Resource.Layout.notification_template_big_media_narrow;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Layout.notification_template_media = global::LoginSystem.Resource.Layout.notification_template_media;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Layout.notification_template_part_chronometer = global::LoginSystem.Resource.Layout.notification_template_part_chronometer;
			global::PCLAppConfig.FileSystemStream.Android.Resource.Layout.notification_template_part_time = global::LoginSystem.Resource.Layout.notification_template_part_time;
			global::PCLAppConfig.FileSystemStream.Android.Resource.String.ApplicationName = global::LoginSystem.Resource.String.ApplicationName;
			global::PCLAppConfig.FileSystemStream.Android.Resource.String.Hello = global::LoginSystem.Resource.String.Hello;
			global::PCLAppConfig.FileSystemStream.Android.Resource.String.status_bar_notification_info_overflow = global::LoginSystem.Resource.String.status_bar_notification_info_overflow;
			global::PCLCrypto.Resource.String.ApplicationName = global::LoginSystem.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::LoginSystem.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::LoginSystem.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::LoginSystem.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int abc_action_bar_embed_tabs = 2131296256;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060003
			public const int notification_action_color_filter = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int notification_icon_bg_color = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int notification_material_background_media_default_color = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int primary_text_default_material_dark = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int ripple_material_light = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int secondary_text_default_material_dark = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int secondary_text_default_material_light = 2131099654;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0004
			public const int compat_button_inset_horizontal_material = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int compat_button_inset_vertical_material = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int compat_button_padding_horizontal_material = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int compat_button_padding_vertical_material = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int compat_control_corner_material = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int notification_action_icon_size = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int notification_action_text_size = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int notification_big_circle_margin = 2131361803;
			
			// aapt resource value: 0x7f0a0001
			public const int notification_content_margin_start = 2131361793;
			
			// aapt resource value: 0x7f0a000c
			public const int notification_large_icon_height = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int notification_large_icon_width = 2131361805;
			
			// aapt resource value: 0x7f0a0002
			public const int notification_main_column_padding_top = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int notification_media_narrow_margin = 2131361795;
			
			// aapt resource value: 0x7f0a000e
			public const int notification_right_icon_size = 2131361806;
			
			// aapt resource value: 0x7f0a0000
			public const int notification_right_side_padding_top = 2131361792;
			
			// aapt resource value: 0x7f0a000f
			public const int notification_small_icon_background_padding = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int notification_small_icon_size_as_large = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int notification_subtext_size = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int notification_top_pad = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int notification_top_pad_large_text = 2131361811;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonSignInStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignUpStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int mail = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_action_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_bg_low = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int notification_bg_low_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notification_bg_low_pressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int notification_bg_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notification_bg_normal_pressed = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int notification_icon_background = 2130837516;
			
			// aapt resource value: 0x7f020010
			public const int notification_template_icon_bg = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int notification_template_icon_low_bg = 2130837521;
			
			// aapt resource value: 0x7f02000d
			public const int notification_tile_bg = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int notify_panel_notification_icon_bg = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ProgressBarStyle = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0016
			public const int action0 = 2131427350;
			
			// aapt resource value: 0x7f0b0013
			public const int action_container = 2131427347;
			
			// aapt resource value: 0x7f0b001a
			public const int action_divider = 2131427354;
			
			// aapt resource value: 0x7f0b0014
			public const int action_image = 2131427348;
			
			// aapt resource value: 0x7f0b0015
			public const int action_text = 2131427349;
			
			// aapt resource value: 0x7f0b0024
			public const int actions = 2131427364;
			
			// aapt resource value: 0x7f0b0005
			public const int async = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int blocking = 2131427334;
			
			// aapt resource value: 0x7f0b000d
			public const int btnDialogEmail = 2131427341;
			
			// aapt resource value: 0x7f0b000f
			public const int btnSignIn = 2131427343;
			
			// aapt resource value: 0x7f0b0011
			public const int btnSignUp = 2131427345;
			
			// aapt resource value: 0x7f0b0017
			public const int cancel_action = 2131427351;
			
			// aapt resource value: 0x7f0b001f
			public const int chronometer = 2131427359;
			
			// aapt resource value: 0x7f0b0026
			public const int end_padder = 2131427366;
			
			// aapt resource value: 0x7f0b0007
			public const int forever = 2131427335;
			
			// aapt resource value: 0x7f0b0021
			public const int icon = 2131427361;
			
			// aapt resource value: 0x7f0b0025
			public const int icon_group = 2131427365;
			
			// aapt resource value: 0x7f0b0020
			public const int info = 2131427360;
			
			// aapt resource value: 0x7f0b0008
			public const int italic = 2131427336;
			
			// aapt resource value: 0x7f0b0000
			public const int line1 = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int line3 = 2131427329;
			
			// aapt resource value: 0x7f0b0019
			public const int media_actions = 2131427353;
			
			// aapt resource value: 0x7f0b0009
			public const int normal = 2131427337;
			
			// aapt resource value: 0x7f0b0023
			public const int notification_background = 2131427363;
			
			// aapt resource value: 0x7f0b001c
			public const int notification_main_column = 2131427356;
			
			// aapt resource value: 0x7f0b001b
			public const int notification_main_column_container = 2131427355;
			
			// aapt resource value: 0x7f0b0012
			public const int progressBar1 = 2131427346;
			
			// aapt resource value: 0x7f0b0022
			public const int right_icon = 2131427362;
			
			// aapt resource value: 0x7f0b001d
			public const int right_side = 2131427357;
			
			// aapt resource value: 0x7f0b0018
			public const int status_bar_latest_event_content = 2131427352;
			
			// aapt resource value: 0x7f0b0002
			public const int text = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int text2 = 2131427331;
			
			// aapt resource value: 0x7f0b001e
			public const int time = 2131427358;
			
			// aapt resource value: 0x7f0b0004
			public const int title = 2131427332;
			
			// aapt resource value: 0x7f0b000e
			public const int txtCreateAccount = 2131427342;
			
			// aapt resource value: 0x7f0b000b
			public const int txtEmail = 2131427339;
			
			// aapt resource value: 0x7f0b000a
			public const int txtFirstName = 2131427338;
			
			// aapt resource value: 0x7f0b0010
			public const int txtOr = 2131427344;
			
			// aapt resource value: 0x7f0b000c
			public const int txtPassword = 2131427340;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int cancel_button_image_alpha = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int status_bar_notification_info_maxnum = 2131165185;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_sign_up = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notification_action = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_action_tombstone = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_media_action = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_media_cancel_action = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_template_big_media = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_template_big_media_custom = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_template_big_media_narrow = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_template_big_media_narrow_custom = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_template_custom_big = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_template_icon_group = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_lines_media = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_media = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_media_custom = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_template_part_chronometer = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int notification_template_part_time = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080002
			public const int ApplicationName = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int Hello = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int status_bar_notification_info_overflow = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050005
			public const int TextAppearance_Compat_Notification = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int TextAppearance_Compat_Notification_Info = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int TextAppearance_Compat_Notification_Media = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int TextAppearance_Compat_Notification_Time = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int TextAppearance_Compat_Notification_Title = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int Widget_Compat_NotificationActionContainer = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Widget_Compat_NotificationActionText = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int dialog_animation = 2131034124;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
